### ISSUE TITLE
Run DQ test for MIRI data

### ISSUE THREAD

**Issue by rizeladiaz** [javerbukh/ST_Validate#3]
Matt,

   When you have some time,  Can you run your DQ test for all the MIRI data in /grp/jwst/ins/regression_test_suite/miri/?  They didn't run this as part of their validation/verification test for build 6 because we assigned it to NIRSpec; however, since this is something your testing tool can do I wanted to use it to do the validation of this step. Let me know when this will be done.

Rossy

**Comment by mattjhill** [comment]
For clarification, do you mean the DQ init step or DQ propagation through the entire pipeline?  I don't have propagation tests for every step yet, but I will try to implement tests for the rest of the 2A steps if necessary.

For the data it self:  There are a lot files in the directory but only three (MIRIM, MIRIFULONG, MIRIFUSHORT) seem to have pipeline output products. Should I run the pipeline for everything in the directory and then test or just test the three which have been run already? 

EDIT:
PIXELDQ propagation is now checked for all steps in the 2A pipeline whose reference files contain a DQ extension (i.e. everything except RefPix, Jump Detection and Ramp Fit)  When I check the MIRIM_M033241-560W_\* files they all pass.

**Comment by rizeladiaz** [comment]
Matt,
  I saw your edit. I was going to suggest to check this only for the steps you have now and only for the data that has products. MIRIM\* are the only ones that have products? If that is the case then you are done.

**Comment by mattjhill** [comment]
For completeness I ran the 2A pipeline on:
jw06161001001_01101_00002_MIRIMAGE_uncal.fits
jw06161001001_01101_00003_MIRIFULONG_uncal.fits
jw07162001001_01101_00001_MIRIFULONG_uncal.fits
jw07163001001_01101_00001_MIRIFUSHORT_uncal.fits
jw07163001001_01101_00002_MIRIFUSHORT_uncal.fits

All of them pass all DQ propagation tests.  Closing the issue.
